### ISSUE TITLE
Syntax error when using pip

### ISSUE THREAD

**Issue by sn3ksoftware** [ColdGrub1384/LibTerm#30]
When I try to use pip (python -m pip), there is a syntax error (line 57):

```python
BUNDLED_MODULES = ['appdirs'. 'chardet', 'colorama', 'python-dateutil', 'distlib', 'distro', 'future', 'idna', 'ipaddress', 'lockfile', 'progress', 'pytoml', 'pytz', 'requests', 'six', 'urllib3', 'webencodings']
```

As you can see, there is supposed to be a comma after `appdirs`, instead of a full-stop. Here is the traceback:

```python
Traceback (most recent call last):
  File "/private/var/containers/Bundle/Application/756DDAF8-7B2B-4140-995F-604E486BDAB9/LibTerm.app/python37.zip/runpy.py", line 183, in _run_module_as_main
  File "/private/var/containers/Bundle/Application/756DDAF8-7B2B-4140-995F-604E486BDAB9/LibTerm.app/python37.zip/runpy.py", line 153, in _get_module_details
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/var/containers/Bundle/Application/756DDAF8-7B2B-4140-995F-604E486BDAB9/LibTerm.app/site-packages/pip.py", line 57
    BUNDLED_MODULES = ['appdirs'. 'chardet', 'colorama', 'python-dateutil', 'distlib', 'distro', 'future', 'idna', 'ipaddress', 'lockfile', 'progress', 'pytoml', 'pytz', 'requests', 'six', 'urllib3', 'webencodings']
                                ^
SyntaxError: invalid syntax
```

**Comment by ColdGrub1384** [comment]
Thank you!

**Comment by sn3ksoftware** [comment]
No problem!
