### ISSUE TITLE
Python frozen after pip install of exif

### ISSUE THREAD

**Issue by aolme** [ColdGrub1384/LibTerm#48]
$ python -m pip install exif

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/private/var/containers/Bundle/Application/6CD9ECDD-99F5-4DE6-87A3-8F97C0C26C45/LibTerm.app/python37.zip/code.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/private/var/containers/Bundle/Application/6CD9ECDD-99F5-4DE6-87A3-8F97C0C26C45/LibTerm.app/python37.zip/traceback.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/private/var/containers/Bundle/Application/6CD9ECDD-99F5-4DE6-87A3-8F97C0C26C45/LibTerm.app/python37.zip/linecache.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/private/var/containers/Bundle/Application/6CD9ECDD-99F5-4DE6-87A3-8F97C0C26C45/LibTerm.app/python37.zip/tokenize.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/private/var/containers/Bundle/Application/6CD9ECDD-99F5-4DE6-87A3-8F97C0C26C45/LibTerm.app/python37.zip/re.py", line 143, in <module>
AttributeError: module 'enum' has no attribute __getattr__

**Comment by Cyber-code** [comment]
I have the same issue (I opened a ticket), it’s seem like the process just before has not ended, if you relaunch the app, it will be ok
